const lessonCatalog = {
  'absolute-value': { title: 'Absolute Value', standard: '6.NS.C.7: Understand ordering and absolute value of rational numbers.', intro: 'Absolute value measures distance from zero. It is never negative because distance is nonnegative.', vocabulary: 'The notation |a| means the distance between a and 0. Opposite numbers, such as -6 and 6, have the same absolute value.', q1: ['What is |-8|?', 8], q2: ['Which statement is true about |-5| and |5|?', 'equal'], q3: ['Evaluate -|-4|.', -4], q4: ['A temperature is -7 degrees C. How many degrees is it from zero?', 7], final: [-12, 12], finalText: 'For a point 12 units from zero, give the two possible coordinates.' },
  'area-triangles-parallelograms': { title: 'Area: Triangles and Parallelograms', standard: '6.G.A.1: Find the area of triangles, special quadrilaterals, and other polygons.', intro: 'Area measures the number of square units inside a two-dimensional figure.', vocabulary: 'A parallelogram has area A = b x h. A triangle has area A = (b x h) / 2. The height must be perpendicular to the base.', q1: ['Find the area of a parallelogram with b = 9 and h = 4.', 36], q2: ['A triangle has b = 10 and h = 6. Is its area 60 square units?', 'no'], q3: ['Find the area of a triangle with b = 8 and h = 5.', 20], q4: ['A parallelogram has area 48 and base 6. Find its height.', 8], final: [27, 20], finalText: 'Final check: triangle b = 9, h = 6; parallelogram b = 5, h = 4. Enter both areas.' },
  'expressions-equations': { title: 'Expressions and Equations', standard: '6.EE.A.2, 6.EE.B.5-7: Write, evaluate, and solve expressions and equations.', intro: 'Variables represent numbers. An expression has operations; an equation states that two quantities are equal.', vocabulary: 'Use the distributive property to rewrite a(b + c) as ab + ac. To solve an equation, use inverse operations and keep both sides balanced.', q1: ['Evaluate 3x + 2 when x = 4.', 14], q2: ['Which equation represents five more than n is 17?', 'n+5=17'], q3: ['Solve x + 9 = 15.', 6], q4: ['Solve 4y = 28.', 7], final: [5, 9], finalText: 'Solve both equations: x + 8 = 13, and 3y = 27.' },
  'integers-add-subtract': { title: 'Integers: Add and Subtract', standard: '6.NS.C.5-6: Interpret and compute with positive and negative numbers.', intro: 'Integers include positive numbers, negative numbers, and zero. A number line models addition as movement.', vocabulary: 'Adding a negative moves left. Subtracting a number is equivalent to adding its opposite: a - b = a + (-b).', q1: ['Evaluate -7 + 12.', 5], q2: ['Which value equals 6 - (-4)?', '10'], q3: ['Evaluate -9 - 5.', -14], q4: ['A bank balance is -12 dollars and you deposit 20 dollars. What is the new balance?', 8], final: [-3, 11], finalText: 'Evaluate both: -8 + 5, and 18 - 7.' },
  'integers-mult-div': { title: 'Integers: Multiply and Divide', standard: '6.NS.B.2-3: Fluently divide multi-digit numbers and apply operations to rational numbers.', intro: 'Multiplication and division with integers follow sign rules. Same signs give a positive result; different signs give a negative result.', vocabulary: 'The product or quotient of two numbers with the same sign is positive. With different signs, it is negative.', q1: ['Evaluate (-6)(4).', -24], q2: ['Is (-35) / (-5) positive or negative?', 'positive'], q3: ['Evaluate 72 / (-8).', -9], q4: ['A loss of 6 points happens in each of 4 rounds. What is the total change?', -24], final: [42, -7], finalText: 'Evaluate: (-6)(-7), and 56 / (-8).' },
  'percent-problems': { title: 'Percent Problems', standard: '6.RP.A.3: Use ratio and rate reasoning to solve percent problems.', intro: 'A percent is a rate per 100. Convert between a percent, decimal, and fraction to solve problems.', vocabulary: 'Percent of means multiply: part = percent x whole. For example, 25% of 80 is 0.25 x 80.', q1: ['Find 25% of 60.', 15], q2: ['Is 0.4 equal to 40%?', 'yes'], q3: ['A 50 dollar item is discounted 20%. What is the discount?', 10], q4: ['18 is what percent of 60?', 30], final: [12, 72], finalText: 'Find 15% of 80, then find the total after adding that amount to 60.' },
  'ratios-proportions': { title: 'Ratios and Proportions', standard: '6.RP.A.1-3: Understand ratios and use equivalent ratios to solve problems.', intro: 'A ratio compares two quantities using the same units. Equivalent ratios describe the same relationship.', vocabulary: 'A unit rate compares a quantity to 1 unit. A proportion is an equation showing that two ratios are equivalent.', q1: ['The ratio of red to blue tiles is 3:5. How many red tiles for 10 blue tiles?', 6], q2: ['Are 4:6 and 2:3 equivalent ratios?', 'yes'], q3: ['Solve 5/8 = x/24.', 15], q4: ['A recipe uses 2 cups of flour for 3 batches. How much for 6 batches?', 4], final: [12, 20], finalText: 'A map scale is 3 cm for 5 km. How many km do 12 cm represent? Then find 4 x 5.' },
  'statistics-mean-median-mode': { title: 'Statistics: Mean, Median, and Mode', standard: '6.SP.A.1-3: Recognize statistical questions and summarize numerical data.', intro: 'A data set can be summarized by measures of center. Each measure tells us something different about typical values.', vocabulary: 'Mean is the sum divided by the number of values. Median is the middle after ordering. Mode is the most frequent value.', q1: ['Find the mean of 4, 6, and 8.', 6], q2: ['What is the median of 2, 5, 9, 12, 20?', 9], q3: ['Find the mode of 3, 4, 4, 7, 8.', 4], q4: ['Find the range of 11, 14, 19, and 25.', 14], final: [6, 9], finalText: 'For 2, 4, 6, 8, enter the mean and median.' },
  'unit-rates': { title: 'Unit Rates', standard: '6.RP.A.2-3: Understand unit rates and use them to solve real-world problems.', intro: 'A unit rate tells how much for one unit. It helps compare prices, speeds, and other rates.', vocabulary: 'To find a unit rate, divide the first quantity by the second so the denominator becomes 1.', q1: ['A car travels 180 miles in 3 hours. What is the speed in miles per hour?', 60], q2: ['Is 12 dollars for 4 notebooks a unit rate?', 'no'], q3: ['A 15 dollar pack has 5 markers. What is the cost per marker?', 3], q4: ['A runner goes 24 miles in 4 hours. What is the unit rate?', 6], final: [8, 45], finalText: 'A 32 dollar item is split among 4 people. Find each share, then find 5 x 9.' },
  'volume-rectangular-prisms': { title: 'Volume: Rectangular Prisms', standard: '6.G.A.2-4: Find the volume of rectangular prisms and use nets to find surface area.', intro: 'Volume measures the space inside a solid figure in cubic units.', vocabulary: 'The volume of a rectangular prism is V = l x w x h. A net unfolds a solid into its faces, helping find surface area.', q1: ['Find V when l = 5, w = 3, and h = 4.', 60], q2: ['Does a 2 x 6 x 7 prism have volume 84 cubic units?', 'yes'], q3: ['A prism has volume 72, length 6, and width 3. Find its height.', 4], q4: ['Find the volume of a cube with side length 5.', 125], final: [48, 80], finalText: 'Find the volume of a 4 x 3 x 4 prism, then its surface area.' }
};

const key = document.body.dataset.lesson;
const lesson = lessonCatalog[key];
const lessonID = `grade6_${key}_v2`;
const stepMinutes = [2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2];
const practiceBank = {
  'absolute-value': [['Find |-3|.', 3], ['Find |7|.', 7], ['Find |-12|.', 12], ['Evaluate -|-5|.', -5], ['Find |0|.', 0], ['Find |-9|.', 9], ['Which is greater: |-4| or |2|?', 4], ['How far is -4 from zero?', 4], ['Evaluate |6 - 10|.', 4], ['Give the positive distance represented by -11.', 11]],
  'area-triangles-parallelograms': [['Parallelogram b=7, h=3. Find A.', 21], ['Triangle b=9, h=4. Find A.', 18], ['Parallelogram b=12, h=5. Find A.', 60], ['Triangle b=6, h=7. Find A.', 21], ['Parallelogram A=45, b=9. Find h.', 5], ['Triangle A=24, b=8. Find h.', 6], ['Triangle b=14, h=3. Find A.', 21], ['Parallelogram b=4.5, h=2. Find A.', 9], ['Triangle b=10, h=8. Find A.', 40], ['Parallelogram A=72, h=8. Find b.', 9]],
  'expressions-equations': [['Evaluate 2x+3 when x=4.', 11], ['Evaluate 5n-1 when n=3.', 14], ['Solve x+7=12.', 5], ['Solve y-6=10.', 16], ['Solve 3m=21.', 7], ['Solve p/4=6.', 24], ['Evaluate 4a+1 when a=2.', 9], ['Solve z+11=20.', 9], ['Solve 2b=18.', 9], ['Evaluate 7-c when c=2.', 5]],
  'integers-add-subtract': [['Evaluate -4+9.', 5], ['Evaluate 8+(-13).', -5], ['Evaluate -6-7.', -13], ['Evaluate 15-(-3).', 18], ['Evaluate -11+4.', -7], ['Evaluate 9-14.', -5], ['Evaluate -2-(-8).', 6], ['Evaluate -16+20.', 4], ['Evaluate 7-(-9).', 16], ['Evaluate -5-6.', -11]],
  'integers-mult-div': [['Evaluate (-3)(7).', -21], ['Evaluate (-8)(-4).', 32], ['Evaluate 54/(-6).', -9], ['Evaluate (-48)/(-8).', 6], ['Evaluate 5(-9).', -45], ['Evaluate (-7)(-7).', 49], ['Evaluate 63/9.', 7], ['Evaluate (-72)/9.', -8], ['Evaluate 11(-2).', -22], ['Evaluate (-100)/(-10).', 10]],
  'percent-problems': [['Find 10% of 80.', 8], ['Find 50% of 36.', 18], ['Find 25% of 40.', 10], ['Find 30% of 90.', 27], ['Find 15% of 60.', 9], ['20 is what percent of 80?', 25], ['Find the 10% discount on $70.', 7], ['Find 40% of 45.', 18], ['Find 5% of 200.', 10], ['12 is what percent of 48?', 25]],
  'ratios-proportions': [['Solve 2/3=x/12.', 8], ['Solve 4/5=x/20.', 16], ['Ratio 3:4; 12 of the second. Find the first.', 9], ['Solve 5/6=x/18.', 15], ['Ratio 2:7; 21 of the second. Find the first.', 6], ['Solve 3/8=x/32.', 12], ['Ratio 4:9; 18 of the second. Find the first.', 8], ['Solve 7/10=x/30.', 21], ['Ratio 5:6; 24 of the second. Find the first.', 20], ['Solve 1/4=x/16.', 4]],
  'statistics-mean-median-mode': [['Find the mean of 2, 4, 6.', 4], ['Find the median of 1, 5, 8.', 5], ['Find the mode of 2, 3, 3, 4.', 3], ['Find the range of 5, 9, 12.', 7], ['Find the mean of 10, 12, 14.', 12], ['Find the median of 3, 7, 9, 11, 20.', 9], ['Find the mode of 1, 2, 2, 4, 5.', 2], ['Find the range of 18, 22, 30.', 12], ['Find the mean of 5, 5, 8, 10.', 7], ['Find the median of 4, 6, 8, 10.', 7]],
  'unit-rates': [['120 miles in 2 hours: find mph.', 60], ['$18 for 6 items: find cost each.', 3], ['45 pages in 5 minutes: find pages/min.', 9], ['$24 for 8 notebooks: find cost each.', 3], ['72 miles in 4 hours: find mph.', 18], ['$35 for 5 tickets: find cost each.', 7], ['90 points in 3 games: find points/game.', 30], ['$42 for 7 pounds: find dollars/pound.', 6], ['56 miles in 8 hours: find mph.', 7], ['$20 for 4 books: find cost each.', 5]],
  'volume-rectangular-prisms': [['Find V: 2 x 3 x 4.', 24], ['Find V: 5 x 2 x 6.', 60], ['V=48, l=4, w=3. Find h.', 4], ['Find V of a cube with side 3.', 27], ['Find V: 7 x 2 x 5.', 70], ['V=90, l=5, w=3. Find h.', 6], ['Find V: 4 x 4 x 2.', 32], ['Find V of a cube with side 4.', 64], ['V=120, l=6, w=4. Find h.', 5], ['Find V: 8 x 2 x 3.', 48]]
};
const firebaseConfig = { apiKey: 'AIzaSyDoXSwni65CuY1_32ZE8B1nwfQO_3VNpTw', authDomain: 'contract-center-llc-10.firebaseapp.com', projectId: 'contract-center-llc-10', storageBucket: 'contract-center-llc-10.firebasestorage.app', messagingSenderId: '323221512767', appId: '1:323221512767:web:6421260f875997dbf64e8a' };
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.firestore();
let currentUser = null, stepsCompleted = {}, currentStep = 0;
let videoWatched = false;
let videoPlayer = null;
const navHeader = document.querySelector('.nav-header');
if (navHeader && !document.getElementById('progress-fill')) navHeader.insertAdjacentHTML('beforeend', '<div class="progress-track" aria-label="Lesson progress"><div id="progress-fill" class="progress-fill"></div></div>');

function info(title, text, button = 'Continue to Practice') { return `<h1>${title}</h1>${text}<div class="standard-box"><strong>Common Core alignment:</strong> ${lesson.standard}</div><div style="text-align:center;"><button class="btn" onclick="submitSimple()">${button}</button></div>`; }
function input(title, concept, question, answer) { return `<h1>${title}</h1><p style="font-size:16px;color:#7f8c8d;">${concept}</p><div class="math-box"><span>${question}</span><input type="text" id="ans-input" class="math-input" placeholder="?"><button class="btn" onclick="submitInput(${JSON.stringify(answer)})">Verify</button></div><div id="fb-box" class="feedback-text"></div>`; }
function practiceSet(title, concept, questions, setKey = 'main') { return `<h1>${title}</h1><p style="font-size:16px;color:#7f8c8d;">${concept}</p><div class="practice-set">${questions.map((item, index) => `<div class="practice-item"><strong>${index + 1}. ${item[0]}</strong><div><input type="text" id="practice-${setKey}-${index}" class="math-input" placeholder="Answer"><button class="btn" onclick="checkPractice('${setKey}',${index},${JSON.stringify(item[1])})">Check</button></div><div id="practice-fb-${setKey}-${index}" class="practice-feedback"></div></div>`).join('')}</div><div id="practice-summary-${setKey}" class="feedback-text">Complete all ${questions.length} problems.</div>`; }
function mcq(title, concept, question, choices, answer) { return `<h1>${title}</h1><p style="font-size:16px;color:#7f8c8d;">${concept}</p><div class="math-box" style="font-size:22px;text-align:center;">${question}</div><div class="choice-row">${choices.map(choice => `<button class="btn ans-btn" onclick="submitMCQ(${JSON.stringify(choice)},${JSON.stringify(answer)})">${choice}</button>`).join('')}</div><div id="fb-box" class="feedback-text"></div>`; }

const lessonData = [
  { title: `1. 🎬 Briefing: ${lesson.title}`, section: 'Core Protocols', html: `<h1>Briefing: ${lesson.title}</h1><p>${lesson.intro}</p><div class="standard-box"><strong>Mission standard:</strong> ${lesson.standard}</div><h2>Watch the lesson briefing</h2><p>Watch the complete video before continuing. The next lesson part unlocks when playback reaches the end.</p><div class="video-container"><div id="lesson-video"></div></div><div id="video-status" class="video-status">Loading video...</div><div style="text-align:center;"><button class="btn secondary" onclick="openLessonVideo()">Open video on YouTube</button> <button id="video-continue" class="btn" disabled title="Watch the video before continuing" onclick="submitVideoBriefing()">I watched the video</button></div>` },
  { title: '2. 📜 Vocabulary and Models', section: 'Level 1: Concepts', html: info('Vocabulary and Models', `<p class="practice-prompt">Before solving, name the mathematical objects and relationships in this lesson.</p><div class="definition-box"><strong>Core idea:</strong><br>${lesson.vocabulary}</div><table class="lesson-table"><thead><tr><th>Ask yourself</th><th>Why it matters</th></tr></thead><tbody><tr><td>What quantities are known?</td><td>Known values determine which operation or formula fits.</td></tr><tr><td>What does the answer represent?</td><td>Units and signs help you catch unreasonable results.</td></tr></tbody></table><div class="hint-box"><strong>Learning habit:</strong> Explain the rule in your own words before using it.</div>`) },
  { title: '3. 🧭 Worked Model', section: 'Level 1: Concepts', html: info('Worked Model', `<p>Watch the reasoning pattern, not just the answer.</p><div class="worked-example"><strong>Step 1: Identify the relationship.</strong><br>${lesson.q1[0]}<br><br><strong>Step 2: Choose the operation.</strong><br>Use the definition and keep units, signs, or place values organized.<br><br><strong>Step 3: Check the result.</strong><br>A correct result should match the size and meaning of the quantities.</div><div class="hint-box"><strong>Try it mentally:</strong> Estimate the answer before opening the next practice check.</div>`) },
  { title: '4. ⚡ Guided Practice Set', section: 'Level 1: Concepts', html: practiceSet('Guided Practice Set', 'Solve all ten examples. Use the worked model, then check each response.', practiceBank[key], 'guided') },
  { title: '5. 🔍 Concept Check', section: 'Level 2: Reasoning', html: mcq('Concept Check', 'Choose the statement that correctly applies the lesson rule.', lesson.q2[0], [lesson.q2[1], lesson.q2[1] === 'yes' ? 'no' : 'not necessarily'], lesson.q2[1]) },
  { title: '6. 📜 Reasoning Strategy', section: 'Level 2: Reasoning', html: info('Reasoning Strategy', `<p>Use this four-step routine on every problem.</p><table class="lesson-table"><thead><tr><th>Step</th><th>Action</th><th>Self-check</th></tr></thead><tbody><tr><td>1. Understand</td><td>Restate the question and label quantities.</td><td>Do I know what the answer means?</td></tr><tr><td>2. Represent</td><td>Draw, write an equation, or organize a table.</td><td>Does the model match the situation?</td></tr><tr><td>3. Solve</td><td>Apply the operation, rule, or formula.</td><td>Did I preserve signs and units?</td></tr><tr><td>4. Reflect</td><td>Estimate or substitute to verify.</td><td>Is the result reasonable?</td></tr></tbody></table>`) },
  { title: '7. ⚡ Independent Practice', section: 'Level 2: Reasoning', html: practiceSet('Independent Practice', 'Solve all ten problems without looking back at the worked model. Estimate before checking.', practiceBank[key], 'independent') },
  { title: '8. 🔍 Error Analysis', section: 'Level 2: Reasoning', html: mcq('Error Analysis', `<p>Debugging is part of doing mathematics. Check the operation, representation, and meaning before accepting an answer.</p><div class="worked-example"><strong>Common mistake:</strong> skipping a unit, sign, regrouping step, or condition can produce a number that looks reasonable but does not answer the question.</div>`, lesson.q4[0], [String(lesson.q4[1]), 'The result cannot be determined'], String(lesson.q4[1])) },
  { title: '9. ⚙️ Applied Simulator', section: 'Level 3: Execution', html: practiceSet('Applied Simulator', `<p>Translate each situation into mathematics. Write a quick estimate first, solve, and interpret the answer with its meaning.</p><div class="hint-box"><strong>Before you submit:</strong> Ask whether the answer is too large, too small, positive, negative, or missing a unit.</div>`, practiceBank[key].slice(0, 5), 'applied') },
  { title: '10. 📝 Mastery Diagnostics', section: 'Level 3: Execution', html: `<h1>Mastery Diagnostics</h1><p>Complete both checks to verify your understanding of the standard.</p><div class="math-box"><span>${lesson.finalText}</span><input type="text" id="final-q1" class="math-input" placeholder="1"><input type="text" id="final-q2" class="math-input" placeholder="2"><button class="btn" onclick="submitFinal()">Submit Log</button></div><div id="fb-box" class="feedback-text"></div>` },
  { title: '11. 🏆 Graduation', section: 'Level 3: Execution', html: `<div style="text-align:center;padding-top:40px;"><h1 style="font-size:80px;margin-bottom:0;">🏆</h1><h1>${lesson.title} Verified!</h1><p style="font-size:18px;max-width:560px;margin:0 auto 30px auto;">You completed the guided models, reasoning checks, applied practice, and Common Core mastery diagnostics for this lesson.</p><button id="mastery-btn" class="btn" style="background:#27ae60;box-shadow:none;" onclick="this.innerText='Logs Saved!';this.disabled=true;">Session Complete</button></div>` }
];

auth.onAuthStateChanged(user => { if (user) { currentUser = user; syncProgress(); } else { document.getElementById('percent-display').textContent = 'Sign in to sync progress'; initSidebar(); showPage(0, true); } });
async function syncProgress() { const ref = db.collection('UserLessonProgress').doc(currentUser.uid).collection('lessons').doc(lessonID); const doc = await ref.get(); stepsCompleted = doc.exists ? doc.data().steps : {}; initSidebar(); updateSidebar(); showPage(0, true); }
async function saveStepProgress(stepIdx, nextIdx) { stepsCompleted[`step_${stepIdx}`] = true; if (currentUser) { const ref = db.collection('UserLessonProgress').doc(currentUser.uid).collection('lessons').doc(lessonID); await ref.set({ steps: stepsCompleted, lastUpdated: new Date() }, { merge: true }); } updateSidebar(); if (stepIdx !== nextIdx && nextIdx < lessonData.length) showPage(nextIdx); }
function initSidebar() { const nav = document.getElementById('nav-list'); let section = '', html = ''; lessonData.forEach((item, index) => { if (item.section !== section) { section = item.section; html += `<div class="nav-section-title">${section}</div>`; } html += `<div id="nav-item-${index}" class="nav-item" onclick="showPage(${index})">${item.title}</div>`; }); nav.innerHTML = html; }
function updateSidebar() { let completed = 0; lessonData.forEach((item, index) => { const el = document.getElementById(`nav-item-${index}`); if (!el) return; const done = !!stepsCompleted[`step_${index}`]; const previous = index === 0 || !!stepsCompleted[`step_${index - 1}`]; if (done) completed++; el.className = 'nav-item'; if (index === currentStep) el.classList.add('active'); else if (done) el.classList.add('completed'); else if (!previous) el.classList.add('locked'); }); const pct = Math.round((completed / (lessonData.length - 1)) * 100); document.getElementById('percent-display').textContent = `Progress: ${Math.min(100, pct)}%`; document.getElementById('progress-fill').style.width = `${Math.min(100, pct)}%`; }
function showPage(index, force = false) { if (index === lessonData.length - 1 && !currentUser) { if (window.showLessonAuthPopup) window.showLessonAuthPopup(); return; } if (!force && index > 0 && !stepsCompleted[`step_${index - 1}`]) return; currentStep = index; videoWatched = !!stepsCompleted.step_0; const box = document.getElementById('dynamic-content'); box.classList.remove('active'); const previous = index > 0 ? `<button class="btn secondary" onclick="showPage(${index - 1})">Back</button>` : '<span></span>'; const next = index < lessonData.length - 1 ? `<span class="muted">Complete this part to continue</span>` : '<span></span>'; box.innerHTML = `<div class="lesson-meta"><span>Part ${index + 1} of ${lessonData.length}</span><strong>About ${stepMinutes[index]} min</strong></div>${lessonData[index].html}<div class="lesson-actions">${previous}${next}</div>`; void box.offsetWidth; box.classList.add('active'); updateSidebar(); if (index === 0 && !stepsCompleted.step_0) initLessonVideo(); if (window.MathJax) MathJax.typesetPromise([box]); }
function submitSimple() { saveStepProgress(currentStep, currentStep + 1); }
function submitVideoBriefing() { if (videoWatched) saveStepProgress(currentStep, currentStep + 1); }
function openLessonVideo() { window.open('https://www.youtube.com/watch?v=1O12A9cgIjY', '_blank', 'noopener'); videoWatched = true; const status = document.getElementById('video-status'); const button = document.getElementById('video-continue'); if (status) status.textContent = 'Video opened in a new tab. Return here after watching to continue.'; if (button) { button.disabled = false; button.textContent = 'I watched the video - continue'; } }
function initLessonVideo() { const status = document.getElementById('video-status'); const button = document.getElementById('video-continue'); if (!status || !button) return; window.onYouTubeIframeAPIReady = () => { videoPlayer = new YT.Player('lesson-video', { videoId: '1O12A9cgIjY', playerVars: { rel: 0, modestbranding: 1 }, events: { onStateChange: event => { if (event.data === YT.PlayerState.ENDED) { videoWatched = true; status.textContent = 'Video complete. You may continue.'; status.style.color = 'var(--success)'; button.disabled = false; button.textContent = 'Continue to the next part'; } }, onError: () => { status.textContent = 'Embedded playback is unavailable here. Open the video on YouTube, watch it, then confirm.'; } } }); }; if (window.YT) window.onYouTubeIframeAPIReady(); else { const script = document.createElement('script'); script.src = 'https://www.youtube.com/iframe_api'; document.head.appendChild(script); } }
function submitMCQ(value, answer) { const fb = document.getElementById('fb-box'); if (String(value).toLowerCase() === String(answer).toLowerCase()) { fb.innerHTML = '<span style="color:var(--success);">Correct! Reasoning aligned.</span>'; setTimeout(() => saveStepProgress(currentStep, currentStep + 1), 700); } else fb.innerHTML = '<span style="color:var(--error);">Incorrect. Recheck the definition and operation.</span>'; }
function submitInput(answer) { const value = document.getElementById('ans-input').value.trim(); const fb = document.getElementById('fb-box'); if (value !== '' && Number(value) === Number(answer)) { fb.innerHTML = '<span style="color:var(--success);">✅ Verified! Calculation locked.</span>'; setTimeout(() => saveStepProgress(currentStep, currentStep + 1), 700); } else fb.innerHTML = '<span style="color:var(--error);">❌ Check the model, signs, and calculation.</span>'; }
const practiceResults = {};
function checkPractice(setKey, index, answer) { const value = document.getElementById(`practice-${setKey}-${index}`).value.trim(); const feedback = document.getElementById(`practice-fb-${setKey}-${index}`); if (!practiceResults[setKey]) practiceResults[setKey] = {}; practiceResults[setKey][index] = value !== '' && Number(value) === Number(answer); feedback.innerHTML = practiceResults[setKey][index] ? '<span style="color:var(--success);">Correct.</span>' : '<span style="color:var(--error);">Try again and check your operation.</span>'; const total = document.querySelectorAll('.practice-item').length; const correct = Object.values(practiceResults[setKey]).filter(Boolean).length; const summary = document.getElementById(`practice-summary-${setKey}`); if (correct === total) { summary.innerHTML = '<span style="color:var(--success);">✅ Practice set complete! Moving on...</span>'; setTimeout(() => saveStepProgress(currentStep, currentStep + 1), 700); } else summary.textContent = `${correct} of ${total} correct. Complete every problem to continue.`; }
function submitFinal() { const first = document.getElementById('final-q1').value.trim(); const second = document.getElementById('final-q2').value.trim(); const fb = document.getElementById('fb-box'); if (Number(first) === Number(lesson.final[0]) && Number(second) === Number(lesson.final[1])) { fb.innerHTML = '<span style="color:var(--success);">✅ Diagnostics passed! Mastery unlocked.</span>'; setTimeout(() => saveStepProgress(currentStep, currentStep + 1), 900); } else fb.innerHTML = '<span style="color:var(--error);">❌ Diagnostics failed. Re-evaluate each quantity.</span>'; }