(function () {
  const script = document.currentScript;
  const parts = location.pathname.split('/');
  const level = parts[parts.length - 2];
  const slug = parts[parts.length - 1].replace(/\.html$/, '');
  const gradeLabel = level === 'k' ? 'Kindergarten' : `Grade ${level.replace('grade', '')}`;
  const title = document.title.replace(/^(?:\d+(st|nd|rd|th)\s*Grade|Grade\s*\d+)\s*:?\s*/i, '').replace(/[^\x00-\x7F]/g, '').trim() || slug.replace(/-/g, ' ');
  const standards = { k: 'NGSS K-PS, K-LS, K-ESS: observe patterns, living things, materials, weather, and the natural world.', grade1: 'NGSS 1-LS, 1-PS, 1-ESS: use observations and evidence to describe living things, materials, light, and space.', grade2: 'NGSS 2-LS, 2-PS, 2-ESS: model interactions, properties of matter, habitats, and Earth systems.', grade3: 'NGSS 3-LS, 3-PS, 3-ESS: develop explanations from evidence about traits, forces, weather, and Earth materials.', grade4: 'NGSS 4-LS, 4-PS, 4-ESS: use models and evidence to explain energy, waves, structures, and Earth processes.', grade5: 'NGSS 5-LS, 5-PS, 5-ESS: explain matter, ecosystems, space systems, and energy using models and evidence.', grade6: 'NGSS Middle School: analyze systems, matter, energy, Earth processes, and life science using evidence.', grade7: 'NGSS Middle School: model ecosystems, forces, matter, Earth systems, and patterns of change.', grade8: 'NGSS Middle School: analyze evidence about climate, evolution, ecology, chemical reactions, and energy.', grade9: 'NGSS High School: explain heredity, DNA, cells, evolution, classification, and biological processes.', grade10: 'NGSS High School: model chemical reactions, bonding, stoichiometry, gases, acids, and conservation of matter.', grade11: 'NGSS High School: investigate physics, Earth systems, energy transfer, waves, and scientific modeling.', grade12: 'NGSS High School: integrate biology, chemistry, physics, Earth science, and environmental systems.' };
  const standard = standards[level] || standards.grade8;
  const lessonID = `science_${level}_${slug}_v1`;
  const firebaseConfig = { apiKey: 'AIzaSyDoXSwni65CuY1_32ZE8B1nwfQO_3VNpTw', authDomain: 'contract-center-llc-10.firebaseapp.com', projectId: 'contract-center-llc-10', storageBucket: 'contract-center-llc-10.firebasestorage.app', messagingSenderId: '323221512767', appId: '1:323221512767:web:6421260f875997dbf64e8a' };
  let currentUser = null, steps = {}, current = 0, videoWatched = false;
  const minutes = [2, 3, 3, 4, 3, 3, 4, 3, 3, 2];
  const safeTitle = title.replace(/[<>]/g, '');
  const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = new URL('science-shell.css', script.src).href; document.head.appendChild(link);
  if (!document.body) document.documentElement.appendChild(document.createElement('body'));
  document.body.innerHTML = `<nav><div class="nav-header"><strong style="font-size:18px;">SCIENCE LAB - ${gradeLabel}</strong><small id="science-percent">Syncing Progress...</small><div class="progress-track"><div id="science-progress-fill" class="progress-fill"></div></div></div><div class="nav-container" id="science-nav"></div></nav><main><div id="science-content" class="content-card"></div></main>`;
  const info = (heading, body) => `<h1>${heading}</h1>${body}<div class="standard-box"><strong>NGSS alignment:</strong> ${standard}</div><div style="text-align:center;"><button class="btn" onclick="scienceSimple()">Continue to Investigation</button></div>`;
  const practice = (heading, body, setKey, count = 5) => `<h1>${heading}</h1>${body}<div class="practice-set">${Array.from({ length: count }, (_, i) => `<div class="practice-item"><strong>${i + 1}. Apply the key idea of ${safeTitle} to a new observation or evidence claim.</strong><div><input type="text" id="science-${setKey}-${i}" class="math-input" placeholder="Answer"><button class="btn" onclick="sciencePractice('${setKey}',${i})">Check</button></div><div id="science-feedback-${setKey}-${i}" class="practice-feedback"></div></div>`).join('')}</div><div id="science-summary-${setKey}" class="feedback-text">Complete all ${count} investigations.</div>`;
  const lessonData = [
    { title: `1. BRIEFING: ${safeTitle}`, section: 'Core Investigation', html: `<h1>Investigation Briefing: ${safeTitle}</h1><p>Science is the practice of asking testable questions, building models, collecting evidence, and revising explanations. This lesson investigates <strong>${safeTitle}</strong>.</p><div class="standard-box"><strong>NGSS alignment:</strong> ${standard}</div><h2>Watch the science briefing</h2><p>Watch the complete briefing before continuing. The next part unlocks after the video is watched.</p><div class="video-container"><div id="science-lesson-video"></div></div><div id="science-video-status" class="video-status">Loading video...</div><div style="text-align:center;"><button class="btn secondary" onclick="openScienceVideo()">Open video on YouTube</button> <button id="science-video-continue" class="btn" disabled title="Watch the video before continuing" onclick="scienceVideoContinue()">I watched the video</button></div>` },
    { title: '2. VOCABULARY AND PHENOMENON', section: 'Level 1: Concepts', html: info('Vocabulary and Phenomenon', `<p class="practice-prompt">Start with what can be observed and measured.</p><div class="definition-box"><strong>Phenomenon focus:</strong><br>${safeTitle} is a scientific idea that can be described with observations, patterns, models, and evidence.</div><table class="lesson-table"><thead><tr><th>Science move</th><th>Question</th></tr></thead><tbody><tr><td>Observe</td><td>What do you notice without explaining it yet?</td></tr><tr><td>Define</td><td>Which terms make the observation precise?</td></tr><tr><td>Predict</td><td>What should happen if the model is correct?</td></tr></tbody></table>`) },
    { title: '3. SYSTEM MODEL', section: 'Level 1: Concepts', html: info('System Model', `<p>Scientists use models to represent things that are too small, large, fast, slow, or complex to observe directly.</p><div class="worked-example"><strong>Build the model:</strong><br>Identify the system, its parts, the energy or matter moving through it, and the interactions between parts. Label what is known and what still needs evidence.</div><div class="hint-box"><strong>Model check:</strong> A useful model explains observations and makes a testable prediction.</div>`) },
    { title: '4. GUIDED INVESTIGATION', section: 'Level 1: Concepts', html: practice('Guided Investigation', `<p>Use the model to make five evidence-based observations. Your teacher or lesson notes can provide the specific phenomenon details.</p><div class="worked-example"><strong>Claim-evidence-reasoning:</strong> State a claim, cite an observation or data point, and explain how the evidence supports the claim.</div>`, 'guided', 5) },
    { title: '5. EVIDENCE CHECK', section: 'Level 2: Reasoning', html: practice('Evidence Check', `<p>Distinguish an observation from an inference, and a supported claim from an unsupported opinion.</p><div class="hint-box"><strong>Remember:</strong> Evidence must be relevant, repeatable, and connected to the question being investigated.</div>`, 'evidence', 5) },
    { title: '6. EXPERIMENTAL DESIGN', section: 'Level 2: Reasoning', html: info('Experimental Design', `<p>A fair investigation changes one factor at a time while measuring a response.</p><table class="lesson-table"><thead><tr><th>Part</th><th>Purpose</th></tr></thead><tbody><tr><td>Independent variable</td><td>The factor intentionally changed.</td></tr><tr><td>Dependent variable</td><td>The response measured or observed.</td></tr><tr><td>Controls</td><td>Conditions kept the same for a fair comparison.</td></tr><tr><td>Repeated trials</td><td>Reduce the effect of random error.</td></tr></tbody></table>`) },
    { title: '7. INDEPENDENT INVESTIGATION', section: 'Level 2: Reasoning', html: practice('Independent Investigation', `<p>Apply the investigation design to five new evidence situations. Explain the relationship, not just the vocabulary.</p>`, 'independent', 5) },
    { title: '8. REAL-WORLD APPLICATION', section: 'Level 3: Applications', html: practice('Real-World Application', `<p>Use the science idea to interpret a real-world system, predict a change, or recommend an evidence-based action.</p>`, 'application', 5) },
    { title: '9. MASTERY DIAGNOSTICS', section: 'Level 3: Applications', html: practice('Mastery Diagnostics', `<p>Complete five final claim-evidence-reasoning checks to demonstrate mastery of ${safeTitle}.</p>`, 'mastery', 5) },
    { title: '10. SCIENCE GRADUATION', section: 'Level 3: Applications', html: `<div style="text-align:center;padding-top:40px;"><h1>SCIENCE GRADUATION</h1><h1>${safeTitle} Verified!</h1><p style="font-size:18px;max-width:560px;margin:0 auto 30px;">You completed the observation, modeling, evidence, investigation, application, and mastery phases for this science lesson.</p><button class="btn" style="background:#2a9d8f;box-shadow:none;">Session Complete</button></div>` }
  ];
  function initNav() { let section = '', html = ''; lessonData.forEach((item, i) => { if (item.section !== section) { section = item.section; html += `<div class="nav-section-title">${section}</div>`; } html += `<div id="science-nav-${i}" class="nav-item" onclick="scienceShow(${i})">${item.title}</div>`; }); document.getElementById('science-nav').innerHTML = html; }
  function updateNav() { let done = 0; lessonData.forEach((item, i) => { const node = document.getElementById(`science-nav-${i}`); const complete = !!steps[`step_${i}`]; const unlocked = i === 0 || !!steps[`step_${i - 1}`]; if (complete) done++; node.className = 'nav-item'; if (i === current) node.classList.add('active'); else if (complete) node.classList.add('completed'); else if (!unlocked) node.classList.add('locked'); }); const pct = Math.min(100, Math.round(done / 9 * 100)); document.getElementById('science-percent').textContent = `Progress: ${pct}%`; document.getElementById('science-progress-fill').style.width = `${pct}%`; }
  function render(index, force) { if (index === lessonData.length - 1 && !currentUser) { if (window.showLessonAuthPopup) window.showLessonAuthPopup(); return; } if (!force && index > 0 && !steps[`step_${index - 1}`]) return; current = index; videoWatched = !!steps.step_0; const box = document.getElementById('science-content'); box.classList.remove('active'); const back = index ? `<button class="btn secondary" onclick="scienceShow(${index - 1})">Back</button>` : '<span></span>'; box.innerHTML = `<div class="lesson-meta"><span>Part ${index + 1} of ${lessonData.length}</span><strong>About ${minutes[index]} min</strong></div>${lessonData[index].html}<div class="lesson-actions">${back}<span style="color:#6b7f88;">Complete this part to continue</span></div>`; void box.offsetWidth; box.classList.add('active'); updateNav(); if (index === 0 && !steps.step_0) initVideo(); }
  async function save(step, next) { steps[`step_${step}`] = true; if (currentUser) { const ref = firebase.firestore().collection('UserLessonProgress').doc(currentUser.uid).collection('lessons').doc(lessonID); await ref.set({ steps, lastUpdated: new Date() }, { merge: true }); } updateNav(); if (next < lessonData.length) render(next); }
  window.scienceShow = i => render(i, false); window.scienceSimple = () => save(current, current + 1); window.scienceVideoContinue = () => { if (videoWatched) save(current, current + 1); }; window.openScienceVideo = () => { window.open('https://www.youtube.com/watch?v=1O12A9cgIjY', '_blank', 'noopener'); videoWatched = true; const b = document.getElementById('science-video-continue'); if (b) { b.disabled = false; b.textContent = 'I watched the video - continue'; b.title = 'Continue to the next part'; } };
  const results = {}; window.sciencePractice = (setKey, index) => { if (!results[setKey]) results[setKey] = {}; results[setKey][index] = document.getElementById(`science-${setKey}-${index}`).value.trim() !== ''; document.getElementById(`science-feedback-${setKey}-${index}`).innerHTML = results[setKey][index] ? '<span style="color:var(--success);">Response recorded. Connect it to evidence.</span>' : '<span style="color:var(--error);">Enter an observation, claim, or explanation.</span>'; const total = document.querySelectorAll('.practice-item').length; const correct = Object.values(results[setKey]).filter(Boolean).length; const summary = document.getElementById(`science-summary-${setKey}`); if (correct === total) { summary.innerHTML = '<span style="color:var(--success);">✅ Investigation complete! Moving on...</span>'; setTimeout(() => save(current, current + 1), 700); } else summary.textContent = `${correct} of ${total} responses recorded. Complete every prompt to continue.`; };
  function initVideo() { const status = document.getElementById('science-video-status'); const button = document.getElementById('science-video-continue'); if (!status || !button) return; window.onYouTubeIframeAPIReady = () => { new YT.Player('science-lesson-video', { videoId: '1O12A9cgIjY', playerVars: { rel: 0, modestbranding: 1 }, events: { onStateChange: e => { if (e.data === YT.PlayerState.ENDED) { videoWatched = true; status.textContent = 'Video complete. You may continue.'; button.disabled = false; button.textContent = 'Continue to the next part'; } }, onError: () => { status.textContent = 'Embedded playback is unavailable here. Open the video on YouTube, watch it, then confirm.'; } } }); }; if (window.YT) window.onYouTubeIframeAPIReady(); else { const s = document.createElement('script'); s.src = 'https://www.youtube.com/iframe_api'; document.head.appendChild(s); } }
  function load(src) { return new Promise((resolve, reject) => { const s = document.createElement('script'); s.src = src; s.onload = resolve; s.onerror = reject; document.head.appendChild(s); }); }
  async function boot() { if (!window.firebase) await load('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js'); if (!window.firebase.auth) await load('https://www.gstatic.com/firebasejs/9.22.0/firebase-auth-compat.js'); if (!window.firebase.firestore) await load('https://www.gstatic.com/firebasejs/9.22.0/firebase-firestore-compat.js'); if (!firebase.apps.length) firebase.initializeApp(firebaseConfig); await load('../../math/lesson-auth-popup.js'); const auth = firebase.auth(); auth.onAuthStateChanged(async user => { currentUser = user; if (user) { const doc = await firebase.firestore().collection('UserLessonProgress').doc(user.uid).collection('lessons').doc(lessonID).get(); steps = doc.exists ? doc.data().steps || {} : {}; initNav(); render(current, true); } else { initNav(); render(0, true); } }); }
  initNav(); render(0, true); boot();
})();
